# Chapter2

## 2.2

In [1]:
50 + 50

[1] 100

In [2]:
1 + 2 + 3 + 4 + 5

[1] 15

In [3]:
a <- 50 + 50

In [4]:
a

[1] 100

In [5]:
b <- a

In [6]:
a

[1] 100

In [7]:
b

[1] 100

In [8]:
a <- 5

In [9]:
a

[1] 5

In [10]:
b

[1] 100

In [11]:
a <- 1

In [12]:
is.vector(a)

[1] TRUE

In [13]:
mode(a)

[1] "numeric"

In [14]:
storage.mode(a)

[1] "double"

In [15]:
class(a)

[1] "numeric"

In [16]:
n <- 100

In [17]:
char <- "ベクトルです "

In [18]:
n1 <- c(2,3,4)

In [19]:
n1

[1] 2 3 4

In [20]:
chr1 <- c("おはよう", "こんにちは", "こんばんは")

In [21]:
chr1

[1] "おはよう"   "こんにちは" "こんばんは"

In [22]:
rm(n1)

In [23]:
rm(chr1)

In [24]:
n1

ERROR: Error in eval(expr, envir, enclos):  オブジェクト 'n1' がありません 


In [25]:
chr1

ERROR: Error in eval(expr, envir, enclos):  オブジェクト 'chr1' がありません 


In [28]:
x <- c(10, 20, 30, 40, 50)

In [29]:
length(x)

[1] 5

In [30]:
a <- 1

In [31]:
a[1]

[1] 1

In [32]:
a[2]

[1] NA

In [33]:
x[2]

[1] 20

In [34]:
x[2:4]

[1] 20 30 40

In [38]:
x[c(1,3,5)]

[1] 10 30 50

In [39]:
x[-1]

[1] 20 30 40 50

In [42]:
x[c(-1,-3,-5)]

[1] 20 40

In [43]:
x[10 < x]

[1] 20 30 40 50

In [44]:
x[30 > x]

[1] 10 20

In [45]:
x[10 < x & x < 40]

[1] 20 30

In [46]:
x[5] <- 0

In [47]:
x

[1] 10 20 30 40  0

In [48]:
x[5] <- "hello"

In [50]:
x

[1] "10"    "20"    "30"    "40"    "hello"

In [52]:
x <- c(1,2,3)
y <- c(4,5,6)
z <- c(7,8,9)

In [54]:
a <- c(x, y, z)

In [55]:
a

[1] 1 2 3 4 5 6 7 8 9

In [57]:
b <- append(x, y)

In [58]:
b

[1] 1 2 3 4 5 6

In [59]:
c <- append(b, y, after=3)

In [60]:
c

[1] 1 2 3 4 5 6 4 5 6

In [61]:
num <- c(1,2,3,4,5,6)

In [62]:
names(num) <- c("one", "two", "trhee", "four", "five", "six")

In [63]:
num

one   two trhee  four  five   six 
    1     2     3     4     5     6

In [64]:
num["one"]

one 
  1

In [65]:
names(num) <- c("1", "2", "3", "4", "5", "6")

In [66]:
num

1 2 3 4 5 6 
1 2 3 4 5 6

In [67]:
names(num) <- NULL

In [68]:
num

[1] 1 2 3 4 5 6

In [69]:
z <- x + y

In [70]:
z

[1] 5 7 9

In [71]:
x <- c(100, 100, 200, 200)
y <- c(0.08, 1.08)
x * y

[1]   8 108  16 216

In [72]:
price <- c(1000, 2000, 3000)
tax_in <- price * 1.08

In [73]:
tax_in

[1] 1080 2160 3240

In [74]:
data1 <- c("1.23", "20.34", "300.45")

In [75]:
mode(data1)

[1] "character"

In [76]:
conv1 <- as.numeric(data1)

In [77]:
storage.mode(conv1)

[1] "double"

In [78]:
conv1

[1]   1.23  20.34 300.45

In [79]:
conv1 <- as.integer(conv1)

In [80]:
mode(conv1)

[1] "numeric"

In [81]:
storage.mode(conv1)

[1] "integer"

In [82]:
conv1

[1]   1  20 300

In [83]:
# 顧客id
id   <- c(1:3)
# 名前
name <- list("秀和太郎",
             "築地花子",
             "宗田解析")
# 住所
add  <- list("中央区築地100-1",
             "中央区築地本町200",
             "中央区日本橋99")

# リストを作成
add_book <- list("顧客リスト", id, name, add)

In [84]:
add_book

[[1]]
[1] "顧客リスト"

[[2]]
[1] 1 2 3

[[3]]
[[3]][[1]]
[1] "秀和太郎"

[[3]][[2]]
[1] "築地花子"

[[3]][[3]]
[1] "宗田解析"


[[4]]
[[4]][[1]]
[1] "中央区築地100-1"

[[4]][[2]]
[1] "中央区築地本町200"

[[4]][[3]]
[1] "中央区日本橋99"

In [85]:
list1 <- add_book[[1]] # リストの第1要素を取得
list2 <- add_book[[2]] # リストの第2要素を取得
list3 <- add_book[[3]] # リストの第3要素を取得
list4 <- add_book[[4]] # リストの第4要素を取得

In [86]:
list1

[1] "顧客リスト"

In [87]:
list2

[1] 1 2 3

In [88]:
list3

[[1]]
[1] "秀和太郎"

[[2]]
[1] "築地花子"

[[3]]
[1] "宗田解析"

In [89]:
list4

[[1]]
[1] "中央区築地100-1"

[[2]]
[1] "中央区築地本町200"

[[3]]
[1] "中央区日本橋99"

In [90]:
cst1_id   <- add_book[[2]][[1]] # 一人目のid
cst1_name <- add_book[[3]][[1]] # 一人目の名前
cst1_add  <- add_book[[4]][[1]] # 一人目の住所

In [91]:
cst1_id

[1] 1

In [92]:
cst1_name

[1] "秀和太郎"

In [93]:
cst1_add

[1] "中央区築地100-1"

In [94]:
var1  <- add_book[c(1,2)]       # リストの第1、第2要素をリストとして取得
var2　<- unlist(add_book[3])    # リストをベクトルに変換して取得

In [95]:
var1

[[1]]
[1] "顧客リスト"

[[2]]
[1] 1 2 3

In [96]:
var2

[1] "秀和太郎" "築地花子" "宗田解析"

In [97]:
add_book[[3]][[1]] <-"築地太郎" # リスト第3要素→サブリスト第1要素を変更

In [99]:
add_book[[3]][[1]]

[1] "築地太郎"

In [100]:
add_book[[3]][[1]] <- NULL      # リスト第3要素→サブリスト第1要素を削除
add_book[[3]]      <- NULL      # リストの第3要素を削除

In [102]:
add_book2 <- list(
                  id   = c(1:3),
                  name = list("秀和太郎", "築地花子", "宗田解析"),
                  add  = list("中央区築地100-1",
                              "中央区築地本町200",
                              "中央区日本橋99")
                  )


In [103]:
add_book2[["name"]]       # 名前付きリスト要素の取り出し
add_book2$"name"          # 名前付きリスト要素の取り出し
add_book2["name"]         # 名前付きリスト要素を名前付きで取り出し
add_book2[["name"]][[1]]  # 名前付きリスト要素のサブ要素の取り出し
add_book2[["name"]][1]    # 名前付きリスト要素のサブ要素をリストに格納して取り出し

[[1]]
[1] "秀和太郎"

[[2]]
[1] "築地花子"

[[3]]
[1] "宗田解析"

[[1]]
[1] "秀和太郎"

[[2]]
[1] "築地花子"

[[3]]
[1] "宗田解析"

$name
$name[[1]]
[1] "秀和太郎"

$name[[2]]
[1] "築地花子"

$name[[3]]
[1] "宗田解析"

[1] "秀和太郎"

[[1]]
[1] "秀和太郎"

In [104]:
vct1 <- c(1, 2, 3, 4, 5, 6)
vct2 <- c(10, 20, 30, 40, 50, 60)
vct3 <- c(100, 200, 300, 400, 500, 600)

In [105]:
mtx1 <- matrix(vct1)             # 行列を作成

In [106]:
mtx1

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5   
[6,] 6

In [107]:
mtx2 <- matrix(vct1, nrow=2)     # 2行の行列を作成

In [108]:
mtx2

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [109]:
mtx3 <- matrix(vct1, ncol=2)     # 2列の行列を作成

In [110]:
mtx3

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [111]:
mtx4 <- matrix(vct1, 2,2)        # 2(行)×2(列)の行列を作成

In [112]:
mtx4

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [113]:
mtx5 <- matrix(vct1,
               nrow=2,           # 2行の行列
               byrow = TRUE)     # 値を行方向に並べ

In [114]:
mtx5

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [115]:
mtx6 <- rbind(vct1, vct2, vct3)  # 3つのベクトルを行として連結する

In [116]:
mtx6

[,1] [,2] [,3] [,4] [,5] [,6]
vct1   1    2    3    4    5    6 
vct2  10   20   30   40   50   60 
vct3 100  200  300  400  500  600

In [117]:
colSums(mtx6)                    # 列の合計を求める

[1] 111 222 333 444 555 666

In [118]:
rowSums(mtx6)                    # 行の合計を求める

vct1 vct2 vct3 
  21  210 2100

In [120]:
mtx7 <- cbind(vct1, vct2, vct3)  # 3つのベクトルを列として連結する
mtx7

vct1 vct2 vct3
[1,] 1    10   100 
[2,] 2    20   200 
[3,] 3    30   300 
[4,] 4    40   400 
[5,] 5    50   500 
[6,] 6    60   600

In [121]:
colSums(mtx7)                    # 列の合計を求める
rowSums(mtx7)                    # 行の合計を求める

vct1 vct2 vct3 
  21  210 2100

[1] 111 222 333 444 555 666

In [122]:
mtx7[1,]   # 1行目を取り出す
mtx7[,1]   # 1列目を取り出す
mtx7[1,1]  # 1行目の1列目の値を取り出す

vct1 vct2 vct3 
   1   10  100

[1] 1 2 3 4 5 6

vct1 
   1

In [123]:
branch <- c(
          "初台店",
          "幡谷店",
          "吉祥寺店",
          "笹塚店",
          "明大前店"
          )

sales <- c(
           2024,
           2164,
           6465,
           2186,
           2348
          )

df <- data.frame(branch=branch, salses=sales)

In [124]:
df

branch   salses
1 初台店   2024  
2 幡谷店   2164  
3 吉祥寺店 6465  
4 笹塚店   2186  
5 明大前店 2348

In [125]:
df$branch # 列データを要素として取り出す
df[[1]]   # 列データを要素として取り出す
df[,1]    # 列データを要素として取り出す
df[1]     # 列データをリストとして取り出す

df[1,]    # 行データをリストとして取り出す

[1] 初台店   幡谷店   吉祥寺店 笹塚店   明大前店
Levels: 吉祥寺店 笹塚店 初台店 幡谷店 明大前店

[1] 初台店   幡谷店   吉祥寺店 笹塚店   明大前店
Levels: 吉祥寺店 笹塚店 初台店 幡谷店 明大前店

[1] 初台店   幡谷店   吉祥寺店 笹塚店   明大前店
Levels: 吉祥寺店 笹塚店 初台店 幡谷店 明大前店

branch  
1 初台店  
2 幡谷店  
3 吉祥寺店
4 笹塚店  
5 明大前店

branch salses
1 初台店 2024

In [128]:
data <- read.table(             # 店舗別売上.txtをdataに代入
  "data/店舗別売上.txt",
  header=TRUE,                  # 1行目は列名であることを指定
  fileEncoding="CP932"
)

In [129]:
data

店舗名       売上高_千円
1  初台店       2024       
2  幡谷店       2164       
3  吉祥寺店     6465       
4  笹塚店       2186       
5  明大前店     2348       
6  下高井戸店   1981       
7  桜上水店     2256       
8  千歳烏山店   3177       
9  仙川店       1861       
10 下高井戸店   3249       
11 つつじヶ丘店 2464       
12 調布店       1975       
13 聖蹟桜ヶ丘店 2496       
14 高幡不動店   3246       
15 八幡山店     2465       
16 上北沢店     1654       
17 下北沢店     2654       
18 府中店       3321       
19 新宿店       6612       
20 永福町店     3189

## 2.3

In [130]:
num <- -10

if(num < 0){       # numは負の値であるか
  num <- num * -1  # -1を掛けて正の値にする
}

In [131]:
num

[1] 10

In [132]:
num <- 10

if(num < 0) {        # numは負の値であるか
  num <- num * -1    # -1を掛けて正の値にする
} else if(num > 0) { # numは正の値であるか
  num <- num * -1    # -1を掛けて負の値にする
}

In [133]:
num

[1] -10

In [134]:
num <- "-10"

if(is.numeric(num) & num < 0){            # numは実数型かつ負の値であるか
    num <- num * -1                       # -1を掛けて正の値にする
  } else if (is.numeric(num) & num > 0) { # numは実数型かつ正の値であるか
    num <- num * -1                       # -1を掛けて負の値にする
  } else {                                # どの条件も成立しない場合 
    num <- as.numeric(num)                # numeric型に変換する
}

In [135]:
num

[1] -10

In [136]:
for (word in c("おはよう", "こんにちは", "こんばんは")) {
    print(word)
}

[1] "おはよう"
[1] "こんにちは"
[1] "こんばんは"


In [139]:
data <- read.table(    # 定着度.txtをdataに代入
  "data/定着度.txt",
  header=T,            # 1行目は列名であることを指定
  fileEncoding="CP932" # 文字コードをShift_JISに指定
)

j <- length(data[1,])  # 列の数を調べる

for(i in c(1:j)) {
  assign(
    sprintf("x%d", i), # xに連番を付けた名前を作る
    data[,i]           # データフレムの1列目から代入する
  )
}

In [140]:
x1

[1] A B C D E F G
Levels: A B C D E F G

In [141]:
x2

[1] 66 70 52 55 73 62 75

In [142]:
x3

[1] 56 55 48 55 60 62 40

In [143]:
x4

[1] 37 45 54 50 62 54 60

In [144]:
show1 <- function() {
  print("Hello!")
}

show1()

[1] "Hello!"


In [145]:
show2 <- function(word1, word2) {
  print(word1)
  print(word2)
}

show2("Rの世界へ", "ようこそ！")

[1] "Rの世界へ"
[1] "ようこそ！"


In [146]:
# 引数を受け取って戻り値を返す関数
taxin <- function(val) {
  tax_in <- val * 1.08
  return(tax_in)
}

tax_in <- taxin(100)

In [147]:
tax_in

[1] 108